### ISSUE TITLE
0.1.0

### ISSUE THREAD

**Issue by driesvints** [BeatSwitch/lock#1]
These things need to be done before a stable 0.1.0 can be released.

**Functionality**
- [x] Action Aliases
- [x] Permission Conditions
- [x] Roles
- [x] Add abstract `ReadOnly`driver
- [x] Extensive review and refactor of `Lock` class

**Issues**
- [x] All issues underneath: https://github.com/BeatSwitch/lock/milestones/0.1.0

**Questions**
- [x] [Rename caller method on Manager class?](https://github.com/BeatSwitch/lock/issues/2)
- [x] [Split Driver interface into Driver\Read and Driver\Write?](https://github.com/BeatSwitch/lock/issues/4)
- [x] [Rename CallerTrait?](https://github.com/BeatSwitch/lock/issues/5)
- [x] [Implement $lock->clear() method?](https://github.com/BeatSwitch/lock/issues/6)
- [x] [Logic of results of allowing or denying permissions](https://github.com/BeatSwitch/lock/issues/7)
- [x] [Split driver interface into CallerDriver and RoleDriver?](https://github.com/BeatSwitch/lock/issues/8)
- [x] [Move interfaces and exceptions where they belong ](https://github.com/BeatSwitch/lock/issues/13)

**Documentation**
- [x] Write more extensive examples on using the Acl and the pre-defined classes that ship with the package. Also make sure to document the logic of the Acl and the hierarchy of permissions.
- [x] How to create drivers (and test them with the LockTestCase)
- [x] Create read-only driver
- [x] Document LockAware trait

**Drivers**
- [x] Write Laravel driver (separate package)

**Package**
- [x] Setup code coverage
- [x] Setup Scrutinizer
- [x] Add `CONTRIBUTORS.md` file
- [x] Add `CHANGELOG.md` file
